---
name: pipeline for NOPCommerce
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 9.0.x
      - name: Restoring dependencies
        run: dotnet restore src/Presentation/nop.web/nop.web.csproj
      - name: Building project
        run: dotnet build src/Presentation/nop.web/nop.web.csproj --configuration Release
      - name: Publishing project
        run: dotnet publish src/Presentation/nop.web/nop.web.csproj --configuration Release
      - name: Running tests
        run: dotnet test src/Presentation/nop.web/nop.web.csproj --logger "trx;LogFileName=test-results.trx"
      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: ./src/Presentation/nop.web/TestResults/test-results.trx
